FROM ubuntu

RUN apt-get -y update && apt-get -y install \
    openjdk-8-jdk   \
    maven           \
    ant             \
    junit           \
    git             \
    vim             \
    make            
